version: '3.7'

services:
  database:
    image: postgres
    container_name: dbignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ignitenode

  app:
    image: ignite/node
    build: .
    container_name: appignite
    ports:
      - 3333:3333
